language: node_js
node_js:
  - '0.10'
  - '0.11'

env:
  global:
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_DATABASE=test
    - POSTGRES_PASSWORD=

addons:
  postgresql: "9.3"

notifications:
  email: false

before_script:
- wget https://github.com/tjwebb/pg-json-schema-export/releases/download/v0.13.0/postbooks_demo_460.json -qO build/postbooks_demo_460.json
- psql -c 'create database mocha;' -U postgres

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: XR2jElipy2t1ERxGlvxoTCm4AIdBnvwYsDKU9H0GaHEhosckgikiScS24uYsQSaLm8QlNCUKH+feDflvOubmu6JLUX0CanN0DZLMUoYxpqRhuEFkh/Kzxdmk3dBZGQuk74u2jatHTL5httEOMzNnX+RKmrsgVneCO7mBEb4Uuh0=
  on:
    tags: true
    repo: tjwebb/waterline-pg-json-import
    all_branches: true
