language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - wget https://github.com/tjwebb/pg-json-schema-export/releases/download/v0.11.4/postbooks_demo_460.json -qO build/postbooks_demo_460.json
